---

- name: Fail if Linux distribution is not supported
  ansible.builtin.fail:
    msg: "Linux distribution is not supported.\nSupported Distribution Families: Archlinux, RedHat, Debian."
  when: ansible_facts.os_family not in ['Archlinux', 'Debian', 'RedHat']

- name: Ensure build dependencies are present
  ansible.builtin.package:
    name: "{{ nvim_build_dependencies[ansible_facts['os_family']] }}"
    state: present
  become: true

- name: Ensure package managed neovim is absent
  ansible.builtin.package:
    name: neovim
    state: absent

- name: Ensure neovim git repo is present
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    dest: "{{ nvim_target_directory }}"
    version: release-0.10

- name: Build and install neovim
  community.general.make:
    chdir: "{{ nvim_target_directory }}"
    params:
      CMAKE_BUILD_TYPE: Release
    target: install
  become: true

- name: Remove neovim build files
  ansible.builtin.file:
    path: "{{ nvim_target_directory }}"
    state: absent
